#language: java
#env:
#  global:
#    - CC_TEST_REPORTER_ID=f43a3053851aed63bd55c901320857ce87d7693419a282d38b0cceac3b7aaf09
#    - CODECOV_TOKEN="85380b17-6b00-42e0-b0b5-e28056d7131a"
#before_script:
#  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#  - chmod +x ./cc-test-reporter
#  - ./cc-test-reporter before-build
#after_script:
#  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 85380b17-6b00-42e0-b0b5-e28056d7131a